name: Build and Deploy

on:
  push:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Load version.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout versions
        if: github.ref == 'refs/heads/master'
        uses: actions/checkout@v4
        with:
          path: "versions"
          ref: refs/heads/gh-pages

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run script
        run: deno run -A ./src/main.ts

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: versions # The folder the action should deploy.
          single-commit: false
          token: ${{ secrets.BOT_PA_TOKEN }}
          git-config-name: "github-actions[bot]"
          git-config-email: "41898282+github-actions[bot]@users.noreply.github.com"
